server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    loadbalancer:
      enabled: true
    gateway:
      routes:
        - id: service1
          uri: lb://SERVICE01
          predicates:
            - Path=/service1/**
          filters:
            - StripPrefix=1
        - id: service2
          uri: lb://SERVICE02
          predicates:
            - Path=/service2/**
          filters:
            - StripPrefix=1